HealXCare/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from hospital import views
# For forgot password views and reset password views
from django.contrib.auth import views as auth_views

# ROOT url file

# All urls paths of different pages will be in url patterns below

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),  # This enables login URLs
    path('activate/<str:uidb64>/<str:token>/', views.activate_account, name='activate'),
    path('login/', views.login_user, name='login'),
    path('redirect-after-google-login/', views.redirect_after_google_login, name='redirect_after_google_login'),
    path('', include('hospital.urls')),
    path('health-advice/', include('HealthAdvice.urls')),
    path('doctor/', include('doctor.urls')),
    path('api/', include('api.urls')),
    path('hospital_admin/', include('hospital_admin.urls')),
    path('chat/', include('ChatApp.urls')),
    path('pharmacy/', include('pharmacy.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    # For forgot password views and reset password views
    # path('reset_password/', auth_views.PasswordResetView.as_view(template_name="reset_password.html"),name="reset-password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_sent.html"),name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"),name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="reset_password_complete.html"),name="password_reset_complete"),
    path('reset_password/', views.resetPassword, name="reset-password"),
    # path('reset-password/',auth_views.PasswordResetView.as_view(template_name="reset_password.html"),name="reset-password"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.debug:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

"""
Forgot password views

1 - User submits email for reset
2 - email is sent to user
3 - user clicks link in email
4 - user is redirected to reset password page

"""

HealthAdvice/urls.py
# HealthAdvice/urls.py
from django.urls import path
from . import views

app_name = "health-advice"  # Namespacing is good!

urlpatterns = [
    path('', views.health_advice, name='health_advice'),  # Updated view name
    path('digestive-disorders/', views.digestive, name='digestive'),
    path('heart-disease/', views.heart_disease, name='heartdisease'),
    path('depression/', views.depression, name='depression'),
    path('asthama/', views.asthama, name='asthama'),
    path('joint-pain/', views.joint_pain, name='jointpain'),
    path('diabetes/', views.diabetes, name='diabetes'),
    path('balasana/', views.balasana, name='balasana'),
    path('pranayam/', views.pranayam, name='pranayam'),
    path('boat-pose/', views.boat_pose, name='boatpose'),
    path('suryanamaskar/', views.suryanamaskar, name='suryanamaskar'),
    path('cobra-pose/', views.cobra_pose, name='cobra-pose'),
    path('tree-pose/', views.tree_pose, name='tree-pose'),
    path('tadasana/', views.tadasana, name='tadasana'),
]

api/urls.py
from django.urls import path
from . import views

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('users/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('', views.getRoutes),
    path('hospital/', views.getHospitals),
    path('hospital/<int:pk>/', views.getHospitalProfile),
]

healthstack/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from hospital import views
# For forgot password views and reset password views
from django.contrib.auth import views as auth_views

# ROOT url file

# All urls paths of different pages will be in url patterns below

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),  # This enables login URLs
    path('activate/<str:uidb64>/<str:token>/', views.activate_account, name='activate'),
    path('login/', views.login_user, name='login'),
    path('redirect-after-google-login/', views.redirect_after_google_login, name='redirect_after_google_login'),
    path('', include('hospital.urls')),
    path('health-advice/', include('HealthAdvice.urls')),
    path('doctor/', include('doctor.urls')),
    path('api/', include('api.urls')),
    path('hospital_admin/', include('hospital_admin.urls')),
    path('chat/', include('ChatApp.urls')),
    path('pharmacy/', include('pharmacy.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    # For forgot password views and reset password views
    # path('reset_password/', auth_views.PasswordResetView.as_view(template_name="reset_password.html"),name="reset-password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_sent.html"),name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"),name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="reset_password_complete.html"),name="password_reset_complete"),
    path('reset_password/', views.resetPassword, name="reset-password"),
    # path('reset-password/',auth_views.PasswordResetView.as_view(template_name="reset_password.html"),name="reset-password"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.debug:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

"""
Forgot password views

1 - User submits email for reset
2 - email is sent to user
3 - user clicks link in email
4 - user is redirected to reset password page

"""

HealthAdvice/models.py
from django.db import models

# Create your models here.

HealthAdvice/views.py
# HealthAdvice/views.py
from django.shortcuts import render

def health_advice(request):  
    patient = None
    if request.user.is_authenticated and hasattr(request.user, 'patient'):
        patient = request.user.patient

    return render(request, 'HealthAdvice/HealthAdvice.html', {"patient": patient})

def digestive(request):  
    patient = None
    if request.user.is_authenticated and hasattr(request.user, 'patient'):
        patient = request.user.patient

    return render(request, 'HealthAdvice/digestive.html', {"patient": patient})

def heart_disease(request):  
    patient = None
    if request.user.is_authenticated and hasattr(request.user, 'patient'):
        patient = request.user.patient

    return render(request, 'HealthAdvice/heartdisease.html', {"patient": patient})

def depression(request):  
    patient = None
    if request.user.is_authenticated and hasattr(request.user, 'patient'):
        patient = request.user.patient

    return render(request, 'HealthAdvice/depression.html', {"patient": patient})

def asthama(request):  
    patient = None
    if request.user.is_authenticated and hasattr(request.user, 'patient'):
        patient = request.user.patient

    return render(request, 'HealthAdvice/asthama.html', {"patient": patient})

def joint_pain(request):  
    patient = None
    if request.user.is_authenticated and hasattr(request.user, 'patient'):
        patient = request.user.patient

    return render(request, 'HealthAdvice/bodypain.html', {"patient": patient})

def diabetes(request):  
    patient = None
    if request.user.is_authenticated and hasattr(request.user, 'patient'):
        patient = request.user.patient

    return render(request, 'HealthAdvice/diabetes.html', {"patient": patient})

def balasana(request):  
    patient = None
    if request.user.is_authenticated and hasattr(request.user, 'patient'):
        patient = request.user.patient

    return render(request, 'HealthAdvice/balasana.html', {"patient": patient})

def pranayam(request):  
    patient = None
    if request.user.is_authenticated and hasattr(request.user, 'patient'):
        patient = request.user.patient

    return render(request, 'HealthAdvice/pranayam.html', {"patient": patient})

def boat_pose(request):  
    patient = None
    if request.user.is_authenticated and hasattr(request.user, 'patient'):
        patient = request.user.patient

    return render(request, 'HealthAdvice/paripurnanavasana.html', {"patient": patient})

def suryanamaskar(request):  
    patient = None
    if request.user.is_authenticated and hasattr(request.user, 'patient'):
        patient = request.user.patient

    return render(request, 'HealthAdvice/suryanamaskar.html', {"patient": patient})

def cobra_pose(request):  
    patient = None
    if request.user.is_authenticated and hasattr(request.user, 'patient'):
        patient = request.user.patient

    return render(request, 'HealthAdvice/cobra.html', {"patient": patient})

def tree_pose(request):  
    patient = None
    if request.user.is_authenticated and hasattr(request.user, 'patient'):
        patient = request.user.patient

    return render(request, 'HealthAdvice/varkasana.html', {"patient": patient})

def tadasana(request):  
    patient = None
    if request.user.is_authenticated and hasattr(request.user, 'patient'):
        patient = request.user.patient

    return render(request, 'HealthAdvice/tadasana.html', {"patient": patient})

templates/HealthAdvice/HealthAdvice.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <script src="https://kit.fontawesome.com/9aa6408b7e.js" crossorigin="anonymous"></script>
    <link type="image/x-icon" href="{% static 'HealthStack-System/images/Normal/favicon.png' %}" rel="icon">
    <link rel="stylesheet" href="{% static 'HealthStack-System/css/Normal/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'HealthStack-System/plugins/Normal/fontawesome/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'HealthStack-System/plugins/Normal/fontawesome/css/all.min.css' %}">
    <!-- <link rel="stylesheet" href="../static/HealthStack-System/css/HealthAdvice/style.css"> -->
    <link rel="stylesheet" href="{% static 'HealthStack-System/css/Normal/style.css' %}">
    <link rel="stylesheet" href="{% static 'HealthStack-System/css/HealthAdvice/style.css' %}">
    <title>Health Advice</title>
</head>

<body>

    <!-- <nav>
        <div class="logo">
            <span class="material-symbols-outlined">
                self_improvement
            </span>
        </div>
        <ul class="navlinks">
            <li> <a href="#">Home</a></li>
            <li> <a href="#ailment">Ailments</a></li>
            <li class="dropdown"> Asanas
                <div class="dropdown-content">
                    <a href="html/balasana.html">Balasana</a>
                    <a href="html/pranayam.html">Pranayam</a>
                    <a href="html/paripurnanavasana.html">Boat Pose</a>
                    <a href="html/suryanamaskar.html">Surya Namaskar</a>
                    <a href="html/cobra.html">Cobra Pose</a>
                    <a href="html/varkasana.html">Tree Pose</a>
                    <a href="html/tadasana.html">Tadasana</a>
                </div>
            </li>
            <li> <a href="#contactus">Contact us</a></li>
        </ul>
        <div class="burger">
            <div class="line1"></div>
            <div class="line2"></div>
            <div class="line3"></div>
        </div>

    </nav> -->

    <!-- Header -->
    {% if not user.is_authenticated%}
    <header class="header">{% include 'navbar_home.html' %}</header>
    {% endif %}
    {% if user.is_authenticated and user.is_doctor %}
    <header class="header">{% include 'doctor-navbar.html' %}</header>
    {% endif %}
    {% if user.is_authenticated and user.is_patient %}
    <header class="header">{% include 'patient_navbar.html' %}</header>
    {% endif %}
    <!-- /Header -->

    <!-- text on home page -->
    <div class="health-advice">
        <header id="showcase" style="background-image: url(../static/images/bg4.jpg);">
            <h1> HealXCare </h1>
            <p>
                Yoga helps you in forming perfect harmony between your body and your mind.
            </p>
            <a href="#ailment" class="button">Read more</a>
        </header>

        <!-- ailments page -->
        <div id="ailment">
            <section class="cards">
                <h1>Select your ailment!</h1>
                <div class="search-box">
                    <div class="search-input">
                        <input type="text" placeholder="Type to search..">
                        <div class="autocom-box">
                        </div>
                        <span class="material-symbols-outlined">search</span>
                    </div>
                </div>
                <div class="cue">
                    <!-- six boxes for six different ailments -->
                    <div class="box">
                        <a href="{% url 'health-advice:digestive' %}">
                            <img src="{% static 'HealthStack-System\images\HealthAdvice\digestive.jpg' %}" alt="digestive">
                            <div class="dis">Digestive disorders</div>
                        </a>
                    </div>

                    <div class="box">
                        <a href="{% url 'health-advice:heartdisease' %}">

                            <img src="{% static 'HealthStack-System\images\HealthAdvice\heart.jpg' %}" alt="heart Diseases">
                            <div class="dis"> Heart problem</div>
                        </a>
                    </div>

                    <div class="box">
                        <a href="{% url 'health-advice:depression' %}">
                            <img src="{% static 'HealthStack-System\images\HealthAdvice\anxiety.jpg' %}" alt="anxiety">
                            <div class="dis"> Anxiety/panic </div>
                        </a>
                    </div>

                    <div class="box">
                        <a href="{% url 'health-advice:asthama' %}">
                            <img src="../static/images/asthma.jpg" alt="asthma">
                            <div class="dis"> Asthma</div>
                        </a>
                    </div>

                    <div class="box">
                        <a href="{% url 'health-advice:jointpain' %}">
                            <img src="../static/images/pain.jpg" alt="back pain">
                            <div class="dis"> Joint pain</div>
                        </a>
                    </div>

                    <div class="box">
                        <a href="{% url 'health-advice:diabetes' %}">
                            <img src="../static/images/diabetes.jpg" alt="diabetes">
                            <div class="dis">Diabetes</div>
                        </a>
                    </div>
                </div>

            </section>
        </div>

        <!-- Contact Us page -->
        <div id="contactus">
            <form action="#" method="POST">
                <section class="contact">
                    <h1>Contact Us</h1>
                    <input type="hidden" name="_captcha" value="false">
                    <input type="text" placeholder="Name" name="name" required>
                    <input type="email" placeholder="Email" name="email" required>
                    <textarea type="text" class="message" name="Message"
                        placeholder="Type your message here"></textarea>
                    <button type="submit"> Send</button>
                </section>
            </form>
        </div>
    </div>

    <!-- <footer class="footer">
        <p>Be a part of our community today.</p><br>
        <div class="foot">
            <a href="#"><i class="fa-brands fa-instagram"></i></a>
            <a href="#"><i class="fa-brands fa-facebook"></i></a>
        </div>

    </footer> -->

    <!-- Footer -->
    {% include 'footer.html' %}
    <!-- /Footer -->
</body>

    <script src="{% static 'HealthStack-System/js/Normal/jquery.min.js' %}"></script>
    <script src="{% static 'HealthStack-System/js/Normal/bootstrap.min.js' %}"></script>

</html>

templates/HealthAdvice/bodypain.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link type="image/x-icon" href="{% static 'HealthStack-System/images/Normal/favicon.png' %}" rel="icon">
    <link rel="stylesheet" href="{% static 'HealthStack-System/css/Normal/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'HealthStack-System/plugins/Normal/fontawesome/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'HealthStack-System/plugins/Normal/fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <title>Body pain/Back pain</title>
    <link rel="stylesheet" href="{% static 'HealthStack-System/css/Normal/style.css' %}">
    <link rel="stylesheet" href="{% static 'HealthStack-System/css/HealthAdvice/ailmentstyle.css' %}">
</head>

<body>

    <!-- Header -->
    {% if not user.is_authenticated%}
    <header class="header">{% include 'navbar_home.html' %}</header>
    {% endif %}
    {% if user.is_authenticated and user.is_doctor %}
    <header class="header">{% include 'doctor-navbar.html' %}</header>
    {% endif %}
    {% if user.is_authenticated and user.is_patient %}
    <header class="header">{% include 'patient_navbar.html' %}</header>
    {% endif %}
    <!-- /Header -->

    <div class="health-advice">
        <div class="title">
            <div id="mainPage">
                <a href="{% url 'health-advice:health_advice' %}">
                    <span>
                        &#x2190
                    </span>
                    Home Page
                </a>
            </div>

            <div class="diseaseTitle">
                <p>
                    Yoga asanas to reduce body pain/back pain
                </p>
            </div>
        </div>

        <div class="HealthAdvice-Container">
            <div class="intro">
                <div>
                    <p>
                        <b>Yoga has countless benefits, a prominent one is that it helps relieve muscle pain and
                            stretches your muscles.</b>
                    </p>
                </div>
                <div>
                    <p>
                        Yoga is a powerful practice that helps us stay active, manage stress, and also help with pain
                        management. Yoga helps because of its strong focus on breathing, which energizes and relaxes our
                        nervous system. Secondly, we move in so many different ways and planes of motion in a yoga class
                        that it works like a complete reset for our posture. And a good posture means less pain. That's
                        why a wholesome yoga practice with a wide variety of poses and mindful breathing helps reduce
                        chronic pain and stiffness in muscles or joints. Here are eight strengthening and stretching
                        postures that are particularly helpful in managing pain in the most common areas of the body.
                    </p>
                </div>
                <div>
                    <img src="{% static 'HealthStack-System\images\HealthAdvice\bodypain.jpg' %}" alt="bodypain">
                </div>

                <div>
                    <p>
                        Yoga provides a more traditional and effective way of leading a healthy life. Yoga helps in the
                        complete toning of the whole body of a person. Doing yoga provides strength and flexibility to
                        the body. Taking medicine for pain has side effects associated with it. Only yoga helps in
                        leading a pain-free life in a natural way. A person who encounter pain like headache, back pain
                        or if there is pain in the entire body then he/she can rely on yoga to provide complete relief
                        from the condition.
                    </p>
                </div>
                <div>
                    <p>
                        There are various asanas in yoga that help in treating the pain of the body in a natural manner.
                        These yoga asanas not only help in alleviating pain but they also improve the quality of life of
                        a person. Yoga releases the stress on the muscles of the body thereby imparting relief. Doing
                        yoga improves blood circulation in the body. Yoga provides the necessary strength to the various
                        muscles of the body. Yoga stimulates the functioning of the nerve thereby providing relief in
                        the body pain. Given below are some of the asanas of yoga that help a person suffering from body
                        pain.
                    </p>
                </div>
            </div>

            <div class="asana">
                <h2>Yoga Poses To Get Rid Of Body/Muscle Pain: </h2>

                <div class="asanaCollection">
                    <div class="box"><img src="{% static 'HealthStack-System\images\HealthAdvice\step3-suryanamaskar.jpg' %}" alt=""><span><a
                                href="{% url 'health-advice:suryanamaskar' %}">Suryanamaskar</a></span></div>
                    <div class="box"><img src="{% static 'HealthStack-System\images\HealthAdvice\step1-suryanamaskar.jpg' %}" alt=""><span><a
                                href="{% url 'health-advice:tadasana' %}">Tadasana</a></span></div>
                    <div class="box"><img src="{% static 'HealthStack-System\images\HealthAdvice\varkasana.jpg' %}" alt=""><span><a
                                href="{% url 'health-advice:tree-pose' %}">Tree Pose</a></span></div>
                </div>
            </div>
        </div>
    </div>

    <!-- Footer -->
    {% include 'footer.html' %}
    <!-- /Footer -->

    <!-- Bootstrap JS (with Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"></script>
    <script src="{% static 'HealthStack-System/js/Normal/jquery.min.js' %}"></script>
    <script src="{% static 'HealthStack-System/js/Normal/bootstrap.min.js' %}"></script>

</body>

</html>

templates/HealthAdvice/diabetes.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link type="image/x-icon" href="{% static 'HealthStack-System/images/Normal/favicon.png' %}" rel="icon">
    <link rel="stylesheet" href="{% static 'HealthStack-System/css/Normal/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'HealthStack-System/plugins/Normal/fontawesome/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'HealthStack-System/plugins/Normal/fontawesome/css/all.min.css' %}">
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <title>Digestive Disorders</title>
    <link rel="stylesheet" href="{% static 'HealthStack-System/css/Normal/style.css' %}">
    <link rel="stylesheet" href="{% static 'HealthStack-System/css/HealthAdvice/ailmentstyle.css' %}">
    <link rel="stylesheet" href="../css/ailmentstyle.css">
</head>

<body>

    <!-- Header -->
    {% if not user.is_authenticated%}
    <header class="header">{% include 'navbar_home.html' %}</header>
    {% endif %}
    {% if user.is_authenticated and user.is_doctor %}
    <header class="header">{% include 'doctor-navbar.html' %}</header>
    {% endif %}
    {% if user.is_authenticated and user.is_patient %}
    <header class="header">{% include 'patient_navbar.html' %}</header>
    {% endif %}
    <!-- /Header -->

    <div class="health-advice">
        <div class="title">
            <div id="mainPage">
                <a href="{% url 'health-advice:health_advice' %}">
                    <span>
                        &#x2190
                    </span>
                    Home Page
                </a>
            </div>

            <div class="diseaseTitle">
                <p>
                    Yoga asanas for Diabetes
                </p>
            </div>
        </div>

        <div class="HealthAdvice-Container">
            <div class="intro">
                <div>
                    <p>
                        Yoga is an additional treatment for those living with diabetes type-2. It helps in improving all
                        the health parameters to promote physical and mental health. Yoga helps in managing diabetes
                        better if you practice yoga for long enough. It will also reduce the risk of complications
                        related to diabetes. Yoga in the early stage of diabetes not only controls your diabetes but
                        also gives the best results for your health. You can practice the best yoga for diabetes to keep
                        your blood sugar levels in control.
                    </p>
                </div>
                <div>
                    <p>
                        Many people with diabetes are now turning to practicing yoga to keep their blood sugar levels
                        under control. Yoga is an ancient known practice that helps in improving overall well-being,
                        reduces stress, lowers blood pressure, and enhances mobility. Adding the simple yogic practice
                        to your daily regime is a way to address diabetes besides medicines. You need to maintain
                        consistency and regularity to get the best results of yoga on your health.
                    </p>
                </div>
                <div>
                    <img src="{% static 'HealthStack-System\images\HealthAdvice\Yoga and Digestion.jpg' %}" alt="">
                </div>
                <div>
                    <h3 style="text-decoration: underline;">
                        Therapeutic Role of Yoga in Diabetes
                    </h3>

                    <p>
                        The key factors that increase the risk of Type -2 Diabetes by 3 times are:
                    </p>
                    <li>Unhealthy diet patterns</li>
                    <li>Lack of physical exercises</li>
                    <li>Psychological stress</li>

                    <p>
                        These factors also pose a risk of coronary heart disease and the risk or severity of diabetes.
                        Therefore it is necessary to have a balance of medicines, physical exercise, and a diabetic diet
                        plan for efficient management of health in diabetic conditions. Yoga is a set of activities that
                        helps in controlling your stress, and emotions and helps in balancing the body to its perfect
                        shape.
                    </p>
                </div>
            </div>

            <div class="cure">
                <h2>Benefits of Yoga For People With Diabetes</h2>

                <ul>
                    People with diabetes are at the risk of developing several health complications. Therefore, diabetes
                    patients need to keep their blood sugar levels in control. Besides medications and insulin therapy,
                    yoga is the best way to adjust your blood sugar levels to normal. Yoga keeps your stress level low,
                    protects against cardiac diseases, prevents diabetic neuropathy, and boosts strength and balance to
                    promote overall health.
                    <br>
                    Starting with yoga exercise for diabetes can be daunting for those who are physically inactive for
                    some time. However, it is a gentle way to improve health and build strength. It also helps in
                    improving your physical and mental well-being through:
                    <li>Keeping your stress levels low</li>
                    <li>Protecting your cardiac health</li>
                    <li>Preventing the risk of diabetic neuropathy</li>
                    <li>Boosting strength and balance</li>
                </ul>
            </div>

            <div class="asana">
                <h2>Yoga poses for better digestion: </h2>

                <div class="asanaCollection">
                    <div class="box"><img src="{% static 'HealthStack-System\images\HealthAdvice\balasana.jpg' %}" alt="Balasana"><span><a href="{% url 'health-advice:balasana' %}">
                                Balasana</a></span></div>
                    <div class="box"><img src="{% static 'HealthStack-System\images\HealthAdvice\tadasana.jpg' %}" alt="Tadasana"><span><a
                                href="{% url 'health-advice:tadasana' %}">Tadasana</a></span></div>
                    <div class="box"><img src="{% static 'HealthStack-System\images\HealthAdvice\step6-suryanamaskar.jpg' %}" alt="Suryanamaskar"><span><a
                                href="{% url 'health-advice:suryanamaskar' %}">Suryanamaskar</a></span></div>

                </div>
            </div>
        </div>
    </div>

    <!-- Footer -->
    {% include 'footer.html' %}
    <!-- /Footer -->
    
     <!-- Bootstrap JS (with Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"></script>
    <script src="{% static 'HealthStack-System/js/Normal/jquery.min.js' %}"></script>
    <script src="{% static 'HealthStack-System/js/Normal/bootstrap.min.js' %}"></script>

</body>

</html>